# Generated by Django 3.1.2 on 2022-04-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_auto_20220422_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='cep',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='banco',
            name='cod',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='banco',
            name='name',
            field=models.TextField(max_length=255),
        ),
    ]
