# Generated by Django 3.1.2 on 2022-04-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_auto_20220422_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_Agencia', models.TextField(max_length=8)),
                ('nome_Agencia', models.CharField(max_length=100)),
                ('telefone_Agencia', models.TextField(max_length=11)),
                ('cep_Agencia', models.TextField(default=0, max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='banco',
            name='cod',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
