# Generated by Django 3.1.2 on 2022-04-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('cod', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False, unique=True)),
                ('name_Agencia', models.CharField(max_length=100)),
                ('tipo_telefone', models.CharField(choices=[('1', 'Fixo'), ('0', 'Celular')], max_length=1)),
                ('telefone_Agencia', models.DecimalField(decimal_places=0, max_digits=11)),
                ('cep_agencia', models.DecimalField(decimal_places=0, max_digits=5, unique=True)),
                ('cod_do_Banco', models.DecimalField(decimal_places=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('cod', models.DecimalField(decimal_places=0, max_digits=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('cep', models.DecimalField(decimal_places=0, max_digits=11)),
            ],
        ),
    ]
