# Generated by Django 3.1.2 on 2022-04-25 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_auto_20220425_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='cod_do_Banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formulario.banco'),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='telefone_Agencia',
            field=models.DecimalField(decimal_places=0, max_digits=11, unique=True),
        ),
    ]
