# Generated by Django 3.1.2 on 2022-04-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0006_auto_20220425_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='cod_do_Banco',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='tipo_telefone',
            field=models.CharField(choices=[('0', 'Celular'), ('1', 'Fixo')], max_length=1),
        ),
    ]
